# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-13

    timeout-minutes: 25

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

  # build:
  #   name: Setup Cocoapods based on provided version
  #   runs-on: macos-latest
  #   steps:
  #   - name: setup-cocoapods
  #     uses: maxim-lobanov/setup-cocoapods@v1
  #     with:
  #       version: 1.9.0


      # with:
        # podfile-path: Pleny-Task/Podfile.lock
      
    - name: Build and Test
      run: xcodebuild test -workspace Pleny-Task.xcworkspace -scheme "Pleny-Task" -destination 'platform=iOS Simulator,name=iPhone 12' 
